name: OTA Update
on:
  push:
    branches: [preview]
  workflow_dispatch: # Allow manual triggering

jobs:
  update:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        profile: [preview]
    steps:
      - uses: actions/checkout@v4
      - uses: expo/expo-github-action@v7
        with:
          expo-version: latest
      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Install EAS CLI
        run: npm install -g eas-cli
      - name: Create OTA Update
        run: |
          # Get the latest commit message for the update message
          COMMIT_MSG=$(git log -1 --pretty=%B)

          # Create and publish the update for the current profile
          eas update --branch ${{ matrix.profile }} --message "$COMMIT_MSG" --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
